#!/usr/bin/env bash
# buildpdf.sh — orchestrates the docs/pdf/howto.md pipeline:
#   resolve (make_latex.jl) → survey+transform (transform.py) → compile
#   (latexmk, clean state) → log triage → validate (validate.py) → package
#   (PDF + autogenerated buildnote.md).
#
# Run from anywhere; assumes the docs environment is instantiated (as
# builddocs.jl leaves it). Standalone: julia --project=docs must work first.
#
# Log contract (howto.md, "Maintaining the pipeline itself"): success is the
# final sentinel line "buildpdf.sh: done — ..."; failure prints
# "buildpdf.sh: FAILED ..."; a log with NEITHER means the process was killed
# or never ran (e.g. an orphaned background launch) — treat it as not-run,
# never as success. Dependent steps here are failure-gated by `set -e`.
set -euo pipefail
trap 'echo "buildpdf.sh: FAILED at line $LINENO (see the stage banner above)" >&2' ERR

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PDFDIR="$ROOT/docs/pdf"
BUILD="$PDFDIR/build"
cd "$ROOT"

echo "== Stage 1: resolve (Documenter LaTeX writer) =="
julia --project=docs docs/make_latex.jl

echo "== Stages 2+3: survey + transform =="
rm -rf "$BUILD"
python3 "$PDFDIR/transform.py" "$ROOT/docs/build_latex" "$BUILD"

echo "== Stage 3.8: preamble probe =="
cd "$BUILD"
sed -n '1,/\\begin{document}/p' main.tex > probe.tex
cat >> probe.tex <<'EOF'
\tableofcontents
\chapter{Probe}\section{Section}
Prose with \texttt{a\_very/long(token)} and specimen glyphs.
\begin{minted}{julia}
f(x) = x
\end{minted}
\begin{tabulary}{\linewidth}{L L} a & b \\ \end{tabulary}
\end{document}
EOF
xelatex -shell-escape -interaction=nonstopmode probe.tex > /dev/null 2>&1 || true
if ! xelatex -shell-escape -interaction=nonstopmode probe.tex > /dev/null 2>&1 \
   || [ "$(grep -c '^!' probe.log)" -ne 0 ]; then
  grep -m5 -A3 '^!' probe.log || true
  echo "buildpdf.sh: preamble probe FAILED (custom.sty/preamble error caught before the full compile)"
  exit 1
fi
rm -f probe.*
echo "probe clean"

echo "== Stage 4: compile (clean state) =="
rm -f main.pdf main.aux main.toc main.out main.fdb_latexmk
latexmk -xelatex -shell-escape -interaction=nonstopmode -halt-on-error main.tex \
  > latexmk.stdout 2>&1 || { tail -40 latexmk.stdout; echo "buildpdf.sh: latexmk failed"; exit 1; }

# Log triage — the hard gates from howto.md Stage 4.
VBOX=$(grep -c "^Overfull \\\\vbox" main.log || true)
MISSCHAR=$(grep -c "^Missing character" main.log || true)
MULTIDEF=$(grep -c "multiply defined" main.log || true)
if [ "$VBOX" -ne 0 ] || [ "$MISSCHAR" -ne 0 ] || [ "$MULTIDEF" -ne 0 ]; then
  grep -m5 -A2 "^Overfull \\\\vbox\|^Missing character\|multiply defined" main.log || true
  echo "buildpdf.sh: Gate 4 FAILED (vbox=$VBOX missing-char=$MISSCHAR multiply-defined=$MULTIDEF)"
  exit 1
fi
[ -s main.toc ] || { echo "buildpdf.sh: empty main.toc (stale aux state?)"; exit 1; }
WORST_HBOX=$(grep "^Overfull \\\\hbox" main.log | sed 's/[^0-9.]*\([0-9.]*\)pt.*/\1/' | sort -rn | head -1)
echo "Gate 4 clean (worst residual Overfull hbox: ${WORST_HBOX:-0}pt)"

echo "== Stage 5: validate =="
python3 "$PDFDIR/validate.py" "$BUILD" main.pdf "$PDFDIR/render_manifest.json"

echo "== Stage 6: package =="
VERSION=$(grep -m1 '^version' "$ROOT/Project.toml" | sed 's/.*"\(.*\)".*/\1/')
SITE=$(grep -m1 '\\newcommand{\\DocMainTitle}' main.tex | sed 's/.*{\\DocMainTitle}{\(.*\)}.*/\1/')
# short package name: version and the UTC build stamp live on the cover page,
# not in the filename
OUT="$PDFDIR/${SITE%.jl}.pdf"
cp main.pdf "$OUT"
# persist the render manifest: next build's check-10 baseline
cp render_manifest.json "$PDFDIR/render_manifest.json"
# editable source bundle (howto.md Stage 6): the build dir IS the bundle;
# the README makes it self-describing
cat > README.md <<EOF
Editable LaTeX source for ${SITE%.jl}.pdf (${SITE} ${VERSION})
(generated by docs/pdf/buildpdf.sh; pipeline: docs/pdf/howto.md).

Contents: main.tex (post-transform), custom.sty (generated), documenter.sty
and preamble.tex (untouched Documenter output), survey.json, render manifest,
and rendered pages under pages/.

Recompile:  latexmk -xelatex -shell-escape -interaction=nonstopmode main.tex
Content changes: regenerate from docs/src via Documenter (bash
docs/pdf/buildpdf.sh) — do not hand-edit content here; layout experiments in
custom.sty are fine but survive only until the next transform run.
EOF

PAGES=$(pdfinfo main.pdf | awk '/^Pages:/{print $2}')
python3 - "$BUILD" "$OUT" "$PAGES" "${WORST_HBOX:-0}" <<'PYEOF'
import json, subprocess, sys, datetime
build, out, pages, hbox = sys.argv[1:5]
s = json.load(open(f"{build}/survey.json"))
def ver(cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True).stdout.strip().split("\n")[0]
    except Exception:
        return "unknown"
note = f"""# Build note — {out.split('/')[-1]} (built {datetime.date.today()})

Generated by docs/pdf/buildpdf.sh (pipeline: docs/pdf/howto.md). {pages} pages, Letter.

## Toolchain
{ver(['xelatex','--version'])}; {ver(['latexmk','--version'])};
Pygments {ver(['pygmentize','-V'])}; DejaVu Sans / DejaVu Sans Mono;
Documenter LaTeX writer (platform="none" via docs/make_latex.jl);
validation: pdftoppm/pdfplumber/pypdf/qpdf.

## Reorganizations relative to docs/make.jl
- parts flattened: {s['parts_flattened']} ({s['parts']} one-chapter parts)
- duplicate labels uniquified: {s['labels_uniquified']} (none were link targets — asserted)
- regrouping candidates (editorial, howto.md Stage 2 — not auto-applied):
  {', '.join(s.get('regroup_candidates') or []) or 'none'}

## Special handling
- {s['code_blocks']} code blocks (longest {s['longest_block_lines']} lines, all wrapped unbreakable);
  {s['chains_glued']} whitespace-adjacent chains glued; {s['colon_glued']} colon-introduced blocks glued
- {s['docstrings_wrapped']} docstrings wrapped (breakable glue between consecutive boxes — rule 8)
- {s['tables']} tabulary tables: prose columns R->L, kept whole at footnotesize
- {s['table_units_kept_together']} table-bearing headings kept with their tables (rule 3, \\needspace);
  {s['tables_glued_to_paragraph']} oversized-extent tables glued to their introducing paragraph
- \\allowbreak after {s['escaped_underscores_prose']} escaped underscores (prose/texttt only)
- largest TOC chapter block: {s['toc_max_chapter_block']} section entries (rule 9 headroom)
- Unicode fallbacks: {s['unicode_fallbacks'] or 'none needed (full DejaVu coverage)'}

## Verification
Gate 4: zero Overfull vbox, zero missing characters, no multiply-defined labels,
TOC populated; worst residual Overfull hbox {hbox}pt.
Gate 5 battery (validate.py): qpdf clean, text extracts on every page (no U+FFFD),
bookmarks present, no near-blank pages, margin ink respected, no code-band
page-boundary crossings, TOC block integrity (rule 9) clean.

## Reproducing
    julia docs/builddocs.jl            # HTML + PDF (set DOCS_PDF=skip to omit)
    bash docs/pdf/buildpdf.sh          # PDF only (docs env must be instantiated)
Content changes regenerate from docs/src — never edit the LaTeX by hand.
"""
open(f"{build}/../buildnote.md", "w").write(note)
PYEOF

echo "buildpdf.sh: done — $OUT ($PAGES pages); buildnote at docs/pdf/buildnote.md"
