#!/usr/bin/env julia
# ===== docs/builddocs.jl — one-command local documentation build
#
#   julia docs/builddocs.jl          (from the repository root)
#   julia builddocs.jl               (from docs/)
#
# Activates the docs environment, dev's the package from the parent directory,
# instantiates, runs make.jl (which builds from docs/src/), and reports where
# the site landed. CI should skip this file and run
# `julia --project=docs docs/make.jl` after its own Pkg setup.

import Pkg

const DOCS = @__DIR__
const PKG  = dirname(DOCS)

Pkg.activate(DOCS)
Pkg.develop(Pkg.PackageSpec(path = PKG))
Pkg.instantiate()

include(joinpath(DOCS, "make.jl"))

const BUILD = get(ENV, "DOCS_BUILD_DIR", "build")
const INDEX = joinpath(DOCS, BUILD, "index.html")
if isfile(INDEX)
    @info "Documentation built successfully" site = INDEX
else
    @warn "make.jl completed but no index.html found — check the build log" dir = joinpath(DOCS, BUILD)
end

# The PDF is regenerated by make.jl above, which is where the stage belongs:
# CI and every scripted rebuild invoke make.jl directly, and a PDF stage that
# lived only in this wrapper let those paths leave a stale tracked PDF behind.
# Nothing to do here but report what make.jl produced.
const PDF = joinpath(DOCS, "pdf", "SmallFloats.pdf")
if isfile(PDF)
    @info "PDF present" pdf = PDF size_kb = round(Int, filesize(PDF) / 1024)
elseif get(ENV, "DOCS_PDF", "") == "skip"
    @info "PDF stage was skipped (DOCS_PDF=skip)"
else
    error("make.jl finished but no PDF at $PDF")
end
